### ISSUE TITLE
Running program error

### ISSUE THREAD

**Issue by code-8888** [Reyhanehne/CVF-SID_PyTorch#11]
PS E:\githubProjects\CVF-SID_PyTorch\src> python test.py --device 0 --config ../models/CVF_SID/SIDD_Val/config.json --resume ../models/CVF_SID/SIDD_Val/model_best.pth
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from torch.distributed.optim import DistributedOptimizer
  File "D:\python3.8\lib\site-packages\torch\distributed\optim\__init__.py", line 8, in <module>
    from .optimizer import DistributedOptimizer
  File "D:\python3.8\lib\site-packages\torch\distributed\optim\optimizer.py", line 8, in <module>
    from torch.distributed.rpc import RRef
ImportError: cannot import name 'RRef' from 'torch.distributed.rpc' (D:\python3.8\lib\site-packages\torch\distributed\rpc\__init__.py)

**Comment by code-8888** [comment]
Operating environment
operating system：windows
python3.8
torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2

**Comment by lhehejunl** [comment]
> Operating environment operating system：windows python3.8 torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2

from torch.distributed.rpc import RRef  这句话注释掉不就行了，我看后面也没用到这句

**Comment by GJW9526** [comment]
不知道为什么总是报错说找不到文件
![image](https://github.com/user-attachments/assets/648848a8-68aa-454a-ae80-e1af94d14455)

**Comment by GJW9526** [comment]
> > 运行环境操作系统：windows python3.8 torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2
> 
> from torch.distributed.rpc import RRef 这句话注释掉不就行了，我看后面也没用到这句

大佬能帮我看看吗
