### ISSUE TITLE
If I want to train on our own dataset

### ISSUE THREAD

**Issue by royaljava** [Reyhanehne/CVF-SID_PyTorch#5]
HI！If I want to train on our own dataset，and how should I prepare data， such as ‘Scene_Instances.txt’

**Comment by myavartanoo** [comment]
Thank you very much for your question.
```self.Validation_Gt``` and ```self.Validation_Noisy``` are the list of GT clean and input noisy images, respectively.
Therefore, you can simply load your list of images and revise the lines 41 and 42 of the [CVF-SID_PyTorch/src/data_loader/data.py ](https://github.com/Reyhanehne/CVF-SID_PyTorch/blob/c89242a4ef5cc98481404192392a6f76e0fb0ec9/src/trainer/trainer.py#L41).
Please not that, line 40 read the names of images so you can replace it with the name list of your images.

**Comment by lulu-165** [comment]
May I ask if i need  images in .png format during the test, or do i only need a .mat file?

**Comment by myavartanoo** [comment]
You can edit lines 41 and 42 of the [CVF-SID_PyTorch/src/data_loader/data.py ](https://github.com/Reyhanehne/CVF-SID_PyTorch/blob/c89242a4ef5cc98481404192392a6f76e0fb0ec9/src/data_loader/data.py#L41) to read your images as a list of .png files or a .mat file.

**Comment by lulu-165** [comment]
When I tested, I read ValidationGtBlocksSrgb.mat and ValidationNoisyBlocksSrgb.mat according to the readme, but there is no content in output/C, output/GT, output/I, output/N_d, output/N_i, what is going on?

**Comment by lulu-165** [comment]
![image](https://user-images.githubusercontent.com/38996467/210207651-0c7977ad-a5c1-4ba7-87ea-a6cf58e4a424.png)
like this.

**Comment by code-8888** [comment]
> ![image](https://user-images.githubusercontent.com/38996467/210207651-0c7977ad-a5c1-4ba7-87ea-a6cf58e4a424.png)喜欢这个。

hello 你这个是怎么跑起来的 为什么我报错呢
```
PS E:\githubProjects\CVF-SID_PyTorch\src> python test.py --device 0 --config ../models/CVF_SID/SIDD_Val/config.json --resume ../models/CVF_SID/SIDD_Val/model_best.pth
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from torch.distributed.optim import DistributedOptimizer
  File "D:\python3.8\lib\site-packages\torch\distributed\optim\__init__.py", line 8, in <module>
    from .optimizer import DistributedOptimizer
  File "D:\python3.8\lib\site-packages\torch\distributed\optim\optimizer.py", line 8, in <module>
    from torch.distributed.rpc import RRef
ImportError: cannot import name 'RRef' from 'torch.distributed.rpc' (D:\python3.8\lib\site-packages\torch\distributed\rpc\__init__.py)  
```
